"Plugin Manager pathogen 
execute pathogen#infect()
"Syntax on 
syntax on

"Ctrl + P fuzzy finder 

"Plugin emmet enabled in normal mode
let g:user_emmet_mode='n'

"Nerdtree plugin configuration
autocmd vimenter * NERDTree

"encoding features 
set encoding=utf-8
"set line no 
set nu

"Set the keymapping for autocomplete the brackets
ino " ""<left>
ino ' ''<left>
ino ( ()<left>
ino [ []<left>
ino { {}<left>
ino {<CR> {<CR>}<ESC>O

"Indentation based on the file types 
" by default, the indent is 2 spaces. 
set shiftwidth=2
set softtabstop=2
set tabstop=2

" for html/rb files, 2 spaces
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab

"for js/coffee/jade/python files, 4 spaces
autocmd Filetype javascript setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype coffeescript setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype jade setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype python setlocal ts=4 sw=4 sts=0 expandtab


"color scheme for my terminal
set background=dark
set t_Co=16
let g:solarized_termcolors=16
colorscheme solarized
set term=screen-256color
